
quarkus:
   datasource:
      db-kind: oracle 
      jdbc:
        driver: shdjk
        url:  sccac
      username: dcsdsd
      password: ddd
# drop and create the database at startup (use `update` to only update the schema)
   hibernate-orm:
      database:
         generation: update
